parameters:
    exelenz_vkphpsdk.oauth.client_id: 2043672
    exelenz_vkphpsdk.oauth.client_secret: 'Nl8t5HlUgGrsC3p7LgUE'
    exelenz_vkphpsdk.oauth.access_token_url: 'https://oauth.vk.com/access_token'
    exelenz_vkphpsdk.oauth.dialog_url: 'https://oauth.vk.com/authorize'
    exelenz_vkphpsdk.oauth.responce_type: 'code'
    exelenz_vkphpsdk.oauth.redirectUri: 'http://local.toplimit.ru/app_dev.php'
    exelenz_vkphpsdk.oauth.scope: 'offline,notify,friends,photos,audio,video,wall'
    exelenz_vkphpsdk.oauth.sessionPrefix: 'vkapi_42_'

services:

    exelenz_vksf2.vkapi.service:
        class: Exelenz\VkSf2Bundle\Model\VkApiService
        arguments:
            - @exelenz_vkphpsdk.oauth.service
            - @exelenz_vkphpsdk.vkapi.service

    exelenz_vkphpsdk.oauth.service:
        class: Exelenz\vkPhpSdk\classes\Oauth2Proxy
        arguments:
            - %exelenz_vkphpsdk.oauth.client_id%
            - %exelenz_vkphpsdk.oauth.client_secret%
            - %exelenz_vkphpsdk.oauth.access_token_url%
            - %exelenz_vkphpsdk.oauth.dialog_url%
            - %exelenz_vkphpsdk.oauth.responce_type%
            - %exelenz_vkphpsdk.oauth.redirectUri%
            - %exelenz_vkphpsdk.oauth.scope%
            - %exelenz_vkphpsdk.oauth.sessionPrefix%
        public: false

    exelenz_vkphpsdk.vkapi.service:
        class: Exelenz\vkPhpSdk\classes\VkPhpSdk
        public: false
